language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
script:
  - cd client && npm i && npm run test

# after_success:
#   - npm run coverage
# language: node_js
# node_js:
#   - 'stable'
# cache:
#   directories:
#     - node_modules
# script:
#   - npm test
#   - npm run report-coverage
